# Generated by Django 5.2.5 on 2025-08-13 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hours_needed', models.DecimalField(decimal_places=1, max_digits=5)),
                ('when', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='directory.skill')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['skill', 'is_active'], name='directory_r_skill_i_023e5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hour_value', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='directory.skill')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['skill', 'is_active'], name='directory_o_skill_i_59642b_idx')],
            },
        ),
    ]
